export const items = [
  {
    title: "001",
    text: "Watux",
    tag: ["design", "styled comp"],
    description:
      "Quisque eleifend, nibh ut gravida luctus, ante eros placerat tortor, non tempor",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "002",
    text: "Dargen",
    tag: ["nft", "polygon"],
    description:
      "Ut tincidunt ultricies nibh, sed dignissim lacus gravida ac. Orci varius natoque.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "003",
    text: "Phanter",
    tag: ["web3", "ethereum"],
    description:
      "Filasd euismod est non lorem scelerisque consequat. Mauris aliquet nibh non iaculis.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "004",
    text: "Spider",
    tag: ["mint", "ethereum"],
    description:
      "Maecenas est ligula, vestibulum eu risus at, dapibus ornare nulla. Nulla imperdiet.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "005",
    text: "Jaguar",
    tag: ["web3", "mint"],
    description:
      "Ut sit amet commodo risus, fikala sit amet molestie erat. Nulla eros elit.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/323/200",
  },
  {
    title: "006",
    text: "Mogul",
    tag: ["design"],
    description:
      "Phasellus sagittis odio id eleifend vestibulum. Vivamus vulputate sapien in.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "007",
    text: "Flokis",
    tag: ["nft", "mint"],
    description:
      "Mauris ultrices arcu a orci gravida maximus. Aliquam a dapibus.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "008",
    text: "Bad tre",
    tag: ["web3"],
    description:
      "Sed fermentum velit urna, vitae aliquam risus fringilla nec. Quisque consectetur dolor.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "009",
    text: "Vlogz",
    tag: ["polygon", "ethereum"],
    description:
      "Donec sed porttitor libero. Quisque vehicula maximus sollicitudin. In hac habitasse platea.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "010",
    text: "Derty",
    tag: ["ethereum", "mint"],
    description:
      "Curabitur rhoncus in turpis semper porttitor. Nam viverra eleifend metus eleifend luctus. corbet flow",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/323/200",
  },
  {
    title: "011",
    text: "Crolander",
    tag: ["mint", "styled comp"],
    description:
      "Pellentesque ipsum leo, interdum sed dolor a, laoreet tempor augue. Aliquam erat palette.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "012",
    text: "Velluto",
    tag: ["styled comp", "design"],
    description:
      "Integer auctor consectetur molestie. Suspendisse tristique erat vitae condimentum luctus. Praesent aliquet.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "013",
    text: "Sdengz",
    tag: ["polygon", "nft"],
    description:
      "Cras nunc purus, rhoncus commodo ipsum at, euismod aliquam 444,4 risus. Fusce tincidunt.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "014",
    text: "Natzukao",
    tag: ["web3", "design"],
    description:
      "Suspendisse eleifend volutpat blandit. In velit tellus, tempor non metus sit amet.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "015",
    text: "Ladybug",
    tag: ["ethereum", "mint"],
    description:
      "Nullam volutpat mollis accumsan. Ut dolor ante, auctor ac felis vel, pellentesque.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/323/200",
  },
];

export const project = [
  {
    title: "Post grid",
    text: "Watux",
    tag: ["design", "styled comp"],
    description: "A post list based on css grid. ",
    link: "/postlist",
    location: "Italy",
    date: "2022-04-25",
    picture: "/images/postgrid.jpg",
  },
  {
    title: "Catalog list",
    text: "Dargen",
    tag: ["design", "styled comp"],
    description: "An example of minimal but efficient use of space",
    link: "/tablelist",
    location: "Italy",
    date: "2022-04-26",
    picture: "/images/tablelist.jpg",
  },
  {
    title: "Accordion",
    text: "Phanter",
    tag: ["design", "styled comp"],
    description:
      "Tenetur ullam rerum ad iusto possimus sequi mollitia dolore sunt quam praesentium, Tenetur ullam rerum. Tenetur ullam rerum ad iusto possimus sequi mollitia dolore sunt quam praesentium, Tenetur ullam rerum.",
    link: "/accordion",
    location: "Italy",
    date: "2022-04-28",
    picture: "/images/accordion.jpg",
  },
  {
    title: "Inline form",
    text: "Spider",
    tag: ["mint", "ethereum"],
    description: "Cool Inline form ",
    link: "/inlineForm",
    location: "Italy",
    date: "2022-05-02",
    picture: "",
  },
  {
    title: "Scrollable List",
    text: "Jaguar",
    tag: ["web3", "mint"],
    description:
      "Splitted enetur ullam rerum ad iusto possimus sequi mollitia dolor.",
    link: "/scrollableList",
    location: "Italy",
    date: "2022-04-30",
    picture: "/images/scrollablelist.jpg",
  },
  {
    title: "NFT home",
    text: "Mogul",
    tag: ["nft"],
    description: "A fancy nft home section",
    link: "/nfthome",
    location: "Italy",
    date: "2022-05-01",
    picture: "",
  },
  {
    title: "CodeBlock",
    text: "Flokis",
    tag: ["nft", "mint"],
    description: "Syntax code block from local file.",
    link: "/syntaxHighlighter",
    location: "Italy",
    date: "2022",
    picture: "",
  },
  {
    title: "ObjectTricks",
    text: "Bad tre",
    tag: ["javascript"],
    description:
      "Sed fermentum velit urna, vitae aliquam risus fringilla nec. Quisque consectetur dolor.",
    link: "/objecttricks",
    location: "Italy",
    date: "2021",
    picture: "",
  },
  {
    title: "Form generator",
    text: "Vlogz",
    tag: ["polygon", "ethereum"],
    description:
      "Donec sed porttitor libero. Quisque vehicula maximus sollicitudin. In hac habitasse platea.",
    link: "/formgenerator",
    location: "Italy",
    date: "2021",
    picture: "",
  },
  {
    title: "Coliseum",
    text: "Derty",
    tag: ["ethereum", "mint"],
    description:
      "Curabitur rhoncus in turpis semper porttitor. Nam viverra eleifend metus eleifend luctus. corbet flow",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "",
  },
  {
    title: "Blocker",
    text: "Crolander",
    tag: ["mint", "styled comp"],
    description:
      "Pellentesque ipsum leo, interdum sed dolor a, laoreet tempor augue. Aliquam erat palette.",
    link: "http://google.com",
    location: "Italy",
    date: "2022",
    picture: "",
  },
  {
    title: "Spotter",
    text: "Velluto",
    tag: ["styled comp", "design"],
    description:
      "Integer auctor consectetur molestie. Suspendisse tristique erat vitae condimentum luctus. Praesent aliquet.",
    link: "http://google.com",
    location: "Italy",
    date: "2022",
    picture: "",
  },
  {
    title: "Anversa",
    text: "Sdengz",
    tag: ["polygon", "nft"],
    description:
      "Cras nunc purus, rhoncus commodo ipsum at, euismod aliquam 444,4 risus. Fusce tincidunt.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "",
  },
  {
    title: "Milano",
    text: "Natzukao",
    tag: ["web3", "design"],
    description:
      "Suspendisse eleifend volutpat blandit. In velit tellus, tempor non metus sit amet.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "",
  },
  {
    title: "Selenium",
    text: "Ladybug",
    tag: ["ethereum", "mint"],
    description:
      "Nullam volutpat mollis accumsan. Ut dolor ante, auctor ac felis vel, pellentesque.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "",
  },
];

export const pricing = [
  {
    job: "developer",
    activity: "Website",
    cost: 1500,
  },
  {
    job: "designer",
    activity: "UI design",
    cost: 1000,
  },
];

export const quadriPF = [
  {
    count: 1915,
    section: "LM022",
    column: "001",
    description: "Codice Attivita'",
  },
  {
    count: 1915,
    section: "LM022",
    column: "002",
    description: "Coefficiente di redditivita' - Percentuale",
  },
  {
    count: 1915,
    section: "LM021",
    column: "001",
    description: "Sussistenza Requisiti accesso regime",
  },
  {
    count: 1915,
    section: "LM021",
    column: "002",
    description: "Assenza cause Ostative Applicazione Regime",
  },
  {
    count: 1857,
    section: "LM042",
    column: "001",
    description: "Differenza",
  },
  {
    count: 1755,
    section: "LM034",
    column: "003",
    description: "Reddito Lordo",
  },
  {
    count: 1754,
    section: "LM022",
    column: "003",
    description: "Totale componenti positivi",
  },
  {
    count: 1735,
    section: "LM036",
    column: "001",
    description: "Reddito Netto",
  },
  {
    count: 1734,
    section: "LM039",
    column: "001",
    description: "Imposta Sostitutiva",
  },
  {
    count: 1708,
    section: "LM020",
    column: "002",
    description: "Casella Autonomo",
  },
  {
    count: 1668,
    section: "LM046",
    column: "001",
    description: "Imposta a Debito",
  },
  {
    count: 1518,
    section: "LM021",
    column: "003",
    description: "Nuova Attivita'",
  },
  {
    count: 1173,
    section: "LM038",
    column: "001",
    description: "Reddito Netto Perdite Soggette Imposta Sostitu.",
  },
  {
    count: 771,
    section: "LM035",
    column: "002",
    description: "Contributi Previdenziali Assistenziali",
  },
  {
    count: 749,
    section: "LM034",
    column: "002",
    description: "Reddito Lordo - Gestione separata autonomi",
  },
  {
    count: 624,
    section: "LM045",
    column: "002",
    description: "Acconti",
  },
  {
    count: 597,
    section: "LM035",
    column: "001",
    description: "Contrib. Previde. assistenziali Versati Periodo",
  },
  {
    count: 562,
    section: "LM038",
    column: "001",
    description: "Redd. Netto Perdite Soggette Imposta Sostit.",
  },
  {
    count: 363,
    section: "LM034",
    column: "002",
    description: "Reddito Lordo -Gestione separata autonomi",
  },
  {
    count: 207,
    section: "LM020",
    column: "001",
    description: "Casella Impresa",
  },
  {
    count: 200,
    section: "LM047",
    column: "001",
    description: "Imposta a Credito",
  },
  {
    count: 174,
    section: "LM035",
    column: "001",
    description: "Contri.Previd. assistenziali Versati Periodo",
  },
  {
    count: 152,
    section: "LM001",
    column: "001",
    description: "Codice attivita'",
  },
  {
    count: 132,
    section: "LM006",
    column: "001",
    description: "Reddito lordo o perdita",
  },
  {
    count: 132,
    section: "LM002",
    column: "001",
    description: "Totale componenti positivi",
  },
  {
    count: 132,
    section: "LM004",
    column: "001",
    description: "Differenza",
  },
  {
    count: 130,
    section: "LM000",
    column: "002",
    description: "Casella Autonomo",
  },
  {
    count: 127,
    section: "LM008",
    column: "001",
    description: "Reddito netto",
  },
  {
    count: 124,
    section: "LM011",
    column: "001",
    description: "Imposta sostitutiva 5%",
  },
  {
    count: 120,
    section: "LM005",
    column: "005",
    description: "Totale componenti negativi",
  },
  {
    count: 117,
    section: "LM034",
    column: "001",
    description: "Reddito Lordo - Artigiani e commercianti",
  },
  {
    count: 112,
    section: "LM007",
    column: "002",
    description: "Contributi previdenziali e assistenziali (2)",
  },
  {
    count: 112,
    section: "LM007",
    column: "001",
    description: "Contributi previdenziali e assistenziali (1)",
  },
  {
    count: 88,
    section: "LM044",
    column: "001",
    description: "Ecced. Impo. Risult. Preced. Dich. Comp. F24",
  },
  {
    count: 70,
    section: "LM043",
    column: "001",
    description: "Eccedenza Imposta risultante Preced. Dichiaraz.",
  },
  {
    count: 66,
    section: "LM010",
    column: "001",
    description: "Redd. Netto Perdite Soggette Impo. Sostitut.",
  },
  {
    count: 59,
    section: "LM010",
    column: "001",
    description: "Redd. Netto Perdite Soggette Imposta Sostituti.",
  },
  {
    count: 53,
    section: "LM043",
    column: "001",
    description: "Eccedenza Imposta risultante Preced. Dichia.",
  },
  {
    count: 42,
    section: "LM034",
    column: "001",
    description: "Reddito Lordo -Artigiani e commercianti",
  },
  {
    count: 22,
    section: "LM000",
    column: "001",
    description: "Casella Impresa",
  },
  {
    count: 21,
    section: "LM041",
    column: "001",
    description: "Ritenute Consorzio",
  },
  {
    count: 15,
    section: "LM049",
    column: "001",
    description: "Eccedenza Contr. Previd. di cui rigo LM7 e LM35",
  },
  {
    count: 10,
    section: "LM023",
    column: "001",
    description: "Codice Attivita'",
  },
  {
    count: 10,
    section: "LM023",
    column: "002",
    description: "Coefficiente di redditivita' - Percentuale",
  },
  {
    count: 7,
    section: "LM023",
    column: "003",
    description: "Totale componenti positivi",
  },
  {
    count: 7,
    section: "LM009",
    column: "003",
    description: "Perdite pregresse",
  },
  {
    count: 5,
    section: "LM049",
    column: "001",
    description: "Eccedenza contr.prev. di cui rigo LM7 e LM35",
  },
  {
    count: 4,
    section: "LM050",
    column: "006",
    description: "Perdite non compensate - Eccedenza 2018",
  },
  {
    count: 4,
    section: "LM023",
    column: "005",
    description: "Reddito per attivita'",
  },
  {
    count: 3,
    section: "LM050",
    column: "005",
    description: "Perdite non compensate - Eccedenza 2017",
  },
  {
    count: 3,
    section: "LM023",
    column: "004",
    description: "Reddito per attivita'",
  },
  {
    count: 2,
    section: "LM037",
    column: "006",
    description: "Perdite pregresse",
  },
  {
    count: 2,
    section: "LM050",
    column: "004",
    description: "Perdite non compensate - Eccedenza 2016",
  },
  {
    count: 1,
    section: "LM009",
    column: "001",
    description: "Perdite pregresse-di cui Misura limitata 80%",
  },
  {
    count: 1,
    section: "LM022",
    column: "004",
    description: "Diritto Autore Correlati",
  },
  {
    count: 1188,
    section: "LM022",
    column: "005",
    description: "Reddito per attivita'",
  },
  {
    count: 1,
    section: "LM050",
    column: "006",
    description: "Perdite non compensate - Eccedenza 2019",
  },
  {
    count: 1,
    section: "LM040",
    column: "002",
    description: "Crediti di Imposta - Redditi prodotti Estero",
  },
  {
    count: 1,
    section: "LM003",
    column: "001",
    description: "Rimanenze finali",
  },
  {
    count: 1,
    section: "LM040",
    column: "015",
    description: "Totale crediti imposta",
  },
  {
    count: 1,
    section: "LM037",
    column: "005",
    description: "Perdite pregresse -di cui Misura piena",
  },
  {
    count: 1,
    section: "LM005",
    column: "001",
    description: "Commi 91 e 92, L. 208/2015",
  },
  {
    count: 1,
    section: "LM009",
    column: "002",
    description: "Perdite pregresse-di cui Misura Piena",
  },
];
