export const items = [
  {
    title: "001",
    text: "Watux",
    tag: ["design", "styled comp"],
    description:
      "Quisque eleifend, nibh ut gravida luctus, ante eros placerat tortor, non tempor",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "002",
    text: "Dargen",
    tag: ["nft", "polygon"],
    description:
      "Ut tincidunt ultricies nibh, sed dignissim lacus gravida ac. Orci varius natoque.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "003",
    text: "Phanter",
    tag: ["web3", "ethereum"],
    description:
      "Filasd euismod est non lorem scelerisque consequat. Mauris aliquet nibh non iaculis.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "004",
    text: "Spider",
    tag: ["mint", "ethereum"],
    description:
      "Maecenas est ligula, vestibulum eu risus at, dapibus ornare nulla. Nulla imperdiet.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "005",
    text: "Jaguar",
    tag: ["web3", "mint"],
    description:
      "Ut sit amet commodo risus, fikala sit amet molestie erat. Nulla eros elit.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/323/200",
  },
  {
    title: "006",
    text: "Mogul",
    tag: ["design"],
    description:
      "Phasellus sagittis odio id eleifend vestibulum. Vivamus vulputate sapien in.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "007",
    text: "Flokis",
    tag: ["nft", "mint"],
    description:
      "Mauris ultrices arcu a orci gravida maximus. Aliquam a dapibus.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "008",
    text: "Bad tre",
    tag: ["web3"],
    description:
      "Sed fermentum velit urna, vitae aliquam risus fringilla nec. Quisque consectetur dolor.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "009",
    text: "Vlogz",
    tag: ["polygon", "ethereum"],
    description:
      "Donec sed porttitor libero. Quisque vehicula maximus sollicitudin. In hac habitasse platea.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "010",
    text: "Derty",
    tag: ["ethereum", "mint"],
    description:
      "Curabitur rhoncus in turpis semper porttitor. Nam viverra eleifend metus eleifend luctus. corbet flow",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/323/200",
  },
  {
    title: "011",
    text: "Crolander",
    tag: ["mint", "styled comp"],
    description:
      "Pellentesque ipsum leo, interdum sed dolor a, laoreet tempor augue. Aliquam erat palette.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "012",
    text: "Velluto",
    tag: ["styled comp", "design"],
    description:
      "Integer auctor consectetur molestie. Suspendisse tristique erat vitae condimentum luctus. Praesent aliquet.",
    link: "http://google.com",
    location: "Italy",
    year: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "013",
    text: "Sdengz",
    tag: ["polygon", "nft"],
    description:
      "Cras nunc purus, rhoncus commodo ipsum at, euismod aliquam 444,4 risus. Fusce tincidunt.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "014",
    text: "Natzukao",
    tag: ["web3", "design"],
    description:
      "Suspendisse eleifend volutpat blandit. In velit tellus, tempor non metus sit amet.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "015",
    text: "Ladybug",
    tag: ["ethereum", "mint"],
    description:
      "Nullam volutpat mollis accumsan. Ut dolor ante, auctor ac felis vel, pellentesque.",
    link: "http://google.com",
    location: "Italy",
    year: "2021",
    picture: "https://picsum.photos/323/200",
  },
];

export const project = [
  {
    title: "Post grid",
    text: "Watux",
    tag: ["design", "styled comp"],
    description: "A post list based on css grid",
    link: "./postlist",
    date: "2022-04-25",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "Catalog list",
    text: "Dargen",
    tag: ["design", "styled comp"],
    description: "An example of minimal but efficient use of space",
    link: "./tablelist",
    location: "Italy",
    date: "2022-04-26",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "Accordion",
    text: "Phanter",
    tag: ["design", "styled comp"],
    description:
      "Tenetur ullam rerum ad iusto possimus sequi mollitia dolore sunt quam praesentium.",
    link: "./accordion",
    location: "Italy",
    date: "2022-04-28",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "Proxyus",
    text: "Spider",
    tag: ["mint", "ethereum"],
    description: "An example of accoridon using useRef hooks",
    link: "http://google.com",
    location: "Italy",
    date: "2022-04-29",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "005",
    text: "Jaguar",
    tag: ["web3", "mint"],
    description:
      "Ut sit amet commodo risus, fikala sit amet molestie erat. Nulla eros elit.",
    link: "http://google.com",
    location: "Italy",
    date: "2022-04-30",
    picture: "https://picsum.photos/323/200",
  },
  {
    title: "006",
    text: "Mogul",
    tag: ["design"],
    description:
      "Phasellus sagittis odio id eleifend vestibulum. Vivamus vulputate sapien in.",
    link: "http://google.com",
    location: "Italy",
    date: "2022-05-01",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "007",
    text: "Flokis",
    tag: ["nft", "mint"],
    description:
      "Mauris ultrices arcu a orci gravida maximus. Aliquam a dapibus.",
    link: "http://google.com",
    location: "Italy",
    date: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "008",
    text: "Bad tre",
    tag: ["web3"],
    description:
      "Sed fermentum velit urna, vitae aliquam risus fringilla nec. Quisque consectetur dolor.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "009",
    text: "Vlogz",
    tag: ["polygon", "ethereum"],
    description:
      "Donec sed porttitor libero. Quisque vehicula maximus sollicitudin. In hac habitasse platea.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "010",
    text: "Derty",
    tag: ["ethereum", "mint"],
    description:
      "Curabitur rhoncus in turpis semper porttitor. Nam viverra eleifend metus eleifend luctus. corbet flow",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "https://picsum.photos/323/200",
  },
  {
    title: "011",
    text: "Crolander",
    tag: ["mint", "styled comp"],
    description:
      "Pellentesque ipsum leo, interdum sed dolor a, laoreet tempor augue. Aliquam erat palette.",
    link: "http://google.com",
    location: "Italy",
    date: "2022",
    picture: "https://picsum.photos/330/200",
  },
  {
    title: "012",
    text: "Velluto",
    tag: ["styled comp", "design"],
    description:
      "Integer auctor consectetur molestie. Suspendisse tristique erat vitae condimentum luctus. Praesent aliquet.",
    link: "http://google.com",
    location: "Italy",
    date: "2022",
    picture: "https://picsum.photos/320/200",
  },
  {
    title: "013",
    text: "Sdengz",
    tag: ["polygon", "nft"],
    description:
      "Cras nunc purus, rhoncus commodo ipsum at, euismod aliquam 444,4 risus. Fusce tincidunt.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "https://picsum.photos/321/200",
  },
  {
    title: "014",
    text: "Natzukao",
    tag: ["web3", "design"],
    description:
      "Suspendisse eleifend volutpat blandit. In velit tellus, tempor non metus sit amet.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "https://picsum.photos/322/200",
  },
  {
    title: "015",
    text: "Ladybug",
    tag: ["ethereum", "mint"],
    description:
      "Nullam volutpat mollis accumsan. Ut dolor ante, auctor ac felis vel, pellentesque.",
    link: "http://google.com",
    location: "Italy",
    date: "2021",
    picture: "https://picsum.photos/323/200",
  },
];
