import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Link from "next/link";
import { project } from "./data";
import Project from "./components/home/project";
import * as S from "./components/commons";

export default function Home() {
  let initialText =
    "A personal repository designed with the purpose of not forgetting (as usual) all that I see around the web and that I promise I will implement in my next project.</br></br>Perhaps in the near future I will add articles to support each project to share its peculiarity. </br></br> Stay tuned!";

  const [text, setText] = useState(initialText);
  const [imagePreview, setImagePreview] = useState("");

  return (
    <div>
      <Head>
        <title>Purple Inspiration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Navbar>
        <Link href="/" passHref>
          <S.Logo>DFHTDI</S.Logo>
        </Link>
      </S.Navbar>
      <div className="home">
        <div className="info">
          <div className="inner">
            <div className="content">
              <h3>Dont Forget How To Do It</h3>
              <p dangerouslySetInnerHTML={{ __html: text }}></p>
            </div>
            <div className="previewWrapper">
              {imagePreview != "" ? <img src={imagePreview} alt="" /> : ""}
            </div>
          </div>
        </div>
        <div className="list">
          <ul>
            {project.map((item, index) => {
              return (
                <Project
                  initialText={initialText}
                  setText={setText}
                  setImagePreview={setImagePreview}
                  key={index}
                  idx={index}
                  title={item.title}
                  text={item.text}
                  picture={item.picture}
                  description={item.description}
                  link={item.link}
                  location={item.location}
                  tags={item.tag}
                  date={item.date}
                ></Project>
              );
            })}
          </ul>
        </div>
      </div>
    </div>
  );
}
